<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GateOps.Application\GateOps.Application.csproj" />
    <ProjectReference Include="..\GateOps.Infrastructure\GateOps.Infrastructure.csproj" />
    <ProjectReference Include="..\GateOps.Domain\GateOps.Domain.csproj" />
  </ItemGroup>

</Project>
